countries/urls.py
from django.urls import path

from .views import (
    CountriesListView,
    CountriesDatatableView,
    CountriesUpdateView,
    countries_delete_view
)

app_name = "countries"

urlpatterns = [
    path('', CountriesListView.as_view(), name='index'),
    path('<int:pk>/update/', CountriesUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', countries_delete_view, name='delete'),
    path('datatable/', CountriesDatatableView.as_view(), name='datatable'),
]

django_serverside_datatable_example/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('countries/', include('countries.urls')),
]

countries/models.py
from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=100, unique=True)
    population = models.BigIntegerField()
    area = models.IntegerField()
    gdp = models.BigIntegerField()

    def __str__(self):
        return self.name

countries/forms.py
from django import forms
from .models import Country

class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ['name', 'population', 'area', 'gdp']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'population': forms.NumberInput(attrs={'class': 'form-control'}),
            'area': forms.NumberInput(attrs={'class': 'form-control'}),
            'gdp': forms.NumberInput(attrs={'class': 'form-control'}),
        }

countries/views.py
from ajax_datatable import AjaxDatatableView
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    UpdateView)

from .forms import CountryForm
from .models import Country


class CountriesListView(TemplateView):
    template_name = 'list.html'


class CountriesDatatableView(AjaxDatatableView):
    model = Country

    column_defs = [
        {'name': 'id', 'visible': False},
        {'name': 'name'},
        {'name': 'area'},
        {'name': 'population'},
        {'name': 'gdp'}
    ]

    def get_initial_queryset(self, request=None):
        return self.model.objects.all()

    def filter_queryset(self, params, qs):
        name = self.request.GET.get('name')
        qs = qs.filter(name__icontains=name)
        return qs


class CountriesUpdateView(UpdateView):
    template_name = 'update.html'
    model = Country
    form_class = CountryForm
    success_url = reverse_lazy('countries:index')


def countries_delete_view(_, pk):
    Country.objects.get(pk=pk).delete()
    return JsonResponse({'success': True})

templates/countries.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Serverside Datatable Example</title>
    <!--Bootstrap5 CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--Datatable Bootstrap5 Theme-->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.bootstrap5.css">
</head>
<body>
<div class="container mx-auto p-3">
    <table id="datatable" class="table table-responsive table-striped table-bordered">
        <thead class="table-dark">
        <tr>
            <th>Name</th>
            <th>Population</th>
            <th>Area (km²)</th>
            <th>GDP ($)</th>
        </tr>
        <tr>
            <th><input type="text" id="name" class="form-control"></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
<!--Bootstrap5 JavaScript-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<!--JQuery-->
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<!--Datatables-->
<script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>
<!--Datatable Bootstrap5 JS Script-->
<script src="https://cdn.datatables.net/2.2.2/js/dataTables.bootstrap5.js"></script>
<script>
    $(document).ready(function () {
        const $name = $('#name');

        const datatable = new DataTable('#datatable', {
            order: [],
            orderCellsTop: true,
            bFilter: false,
            iDisplayLength: 10,
            lengthChange: false,
            processing: true,
            serverSide: true,
            ajax: {
                url: "{% url 'countries:datatable' %}",
                data: function (params) {
                    params.name = $name.val()
                },
            },
            columns: [
                {data: "name"},
                {data: "area"},
                {data: "population"},
                {data: "gdp"}
            ]
        });

        $name.on('keyup', function () {
            datatable.columns(0).search($(this).val()).draw();
        });
    })
</script>
</body>
</html>

templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Serverside Datatable Example</title>
    <!--Bootstrap5 CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--Datatable Bootstrap5 Theme-->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.bootstrap5.css">
    <style>
        tr {
            vertical-align: baseline;
        }

        td:not(:last-child) {
            cursor: pointer;
        }

        .toast-container {
            z-index: 2000 !important;
        }
    </style>
</head>
<body>
<div class="container mx-auto p-3">
    <table id="datatable" class="table table-responsive table-striped table-bordered">
        <thead class="table-dark">
        <tr>
            <th>Name</th>
            <th>Population</th>
            <th>Area (km²)</th>
            <th>GDP ($)</th>
            <!--Extra column for button group-->
            <th></th>
        </tr>
        <tr>
            <th><input type="text" id="name" class="form-control"></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <!--Modal-->
    <div id="confirmation-modal" class="modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fs-3 text-uppercase text-danger">warning</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <span>Are you sure you want to delete it?</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button id="modal-submit" type="button" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Toast-->
<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="toast" class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
                Object deleted successfully
            </div>
            <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>
<!--Bootstrap5 JavaScript-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<!--JQuery-->
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<!--Datatables-->
<script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>
<!--Datatable Bootstrap5 JS Script-->
<script src="https://cdn.datatables.net/2.2.2/js/dataTables.bootstrap5.js"></script>
<script>
    $(document).ready(function () {
        const $name = $('#name');

        const modal = new bootstrap.Modal($('#confirmation-modal'));
        const toast = new bootstrap.Toast($('#toast'));

        const datatable = new DataTable('#datatable', {
            order: [],
            orderCellsTop: true,
            bFilter: false,
            iDisplayLength: 10,
            lengthChange: false,
            processing: true,
            serverSide: true,
            ajax: {
                url: "{% url 'countries:datatable' %}",
                data: function (params) {
                    params.name = $name.val()
                },
            },
            columns: [
                {data: "name"},
                {data: "population"},
                {data: "area"},
                {data: "gdp"},
                {
                    data: null,
                    orderable: false,
                    render: function (data) {
                        return '<div class="btn-group d-flex justify-content-center" role="group" aria-label="Basic example">\n' +
                            '<a style=\'width: 80px\'' + `href="${data.pk}/update/"` + 'class="btn btn-primary">Update</a>\n' +
                            '<button style=\'width: 80px\' type="button" class="btn btn-danger">Delete</button>\n' +
                            '</div>'
                    }
                }
            ],
            createdRow: function (row, data) {
                $(row).find('td:not(:last-child)').on('click', function () {
                    document.location.href = `${data.pk}/update/`;
                });

                $(row).find('.btn-danger').on('click', function () {
                    modal.show();

                    $('#modal-submit').on('click', function () {
                        modal.hide();

                        $.ajax({
                            url: `${data.pk}/delete/`,
                            method: "DELETE", headers: {
                                "X-CSRFToken": "{{ csrf_token }}"
                            },
                            success: function () {
                                datatable.ajax.reload();
                                toast.show();
                            }
                        });
                    })
                })
            }
        });

        $name.on('keyup', function () {
            datatable.columns(0).search($(this).val()).draw();
        });
    })
</script>
</body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--Bootstrap5 CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Update {{form.instance.name}}</title>
</head>
<body>
<div class="container mx-auto p-3">
    <form method="post">
        {% csrf_token %}
        {{ form.id }}
        <div class="mb-3">
            <label>Name</label>
            {{ form.name }}
        </div>
        <div class="mb-3">
            <label>Population</label>
            {{ form.population }}
        </div>
        <div class="mb-3">
            <label>Area</label>
            {{ form.area }}
        </div>
        <div class="mb-3">
            <label>GDP</label>
            {{ form.gdp }}
        </div>
        <div>
            <button class="btn btn-success float-end" type="submit">Save</button>
        </div>
    </form>
</div>
<!--Bootstrap5 JavaScript-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<!--JQuery-->
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
</body>
</html>